name: xkcd_comics_viewer
description: Viewer application for xkcd (https://xkcd.com/) comics.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.3.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  mobx: ^2.1.0
  flutter_mobx: ^2.0.6+4
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  json_annotation: ^4.6.0
  cached_network_image: ^3.2.2
  photo_view: ^0.14.0
  easy_localization: ^3.0.1
  easy_localization_loader:
    git: https://github.com/aissat/easy_localization_loader.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+3
  retrofit_generator: ^4.0.3+2
  json_serializable: ^6.3.2
  mockito: ^5.3.1

flutter:
  uses-material-design: true