name: xkcd_comics_viewer
description: Viewer application for xkcd (https://xkcd.com/) comics.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  easy_localization: 3.0.0
  easy_localization_loader: 1.0.0
  mobx: 2.0.1
  flutter_mobx: 2.0.0
  get_it: 6.0.0
  theme_provider: 0.5.0
  google_fonts: 2.0.0
  hive: 2.0.2
  hive_flutter: 1.0.0
  hive_generator: 1.0.1
  retrofit: 2.0.0-beta1
  logger: 1.0.0
  json_annotation: 4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.12.2
  mobx_codegen: 2.0.1+2
  retrofit_generator: 2.0.0-beta3
  json_serializable: 4.1.0
  built_value_generator: 8.0.4

flutter:
  uses-material-design: true