// Mocks generated by Mockito 5.0.4 from annotations
// in xkcd_comics_viewer/test/presentation/screens/widgets/comic_error_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import '../../../commons/function_handler.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FunctionHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctionHandler extends _i1.Mock implements _i2.FunctionHandler {
  MockFunctionHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic Function() get simpleMockFunction => (super.noSuchMethod(Invocation.getter(#simpleMockFunction), returnValue: () => null) as dynamic Function());

  @override
  set simpleMockFunction(dynamic Function()? _simpleMockFunction) =>
      super.noSuchMethod(Invocation.setter(#simpleMockFunction, _simpleMockFunction), returnValueForMissingStub: null);

  @override
  _i3.Future<dynamic> Function() get simpleFutureMockFunction =>
      (super.noSuchMethod(Invocation.getter(#simpleFutureMockFunction), returnValue: () => Future<dynamic>.value(null)) as _i3.Future<dynamic> Function());

  @override
  set simpleFutureMockFunction(_i3.Future<dynamic> Function()? _simpleFutureMockFunction) =>
      super.noSuchMethod(Invocation.setter(#simpleFutureMockFunction, _simpleFutureMockFunction), returnValueForMissingStub: null);
}
